# -*- coding: utf-8 -*-
"""DataAnalysisHelper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tbr6rB2etAwTpKuxLK-xLiCEqdbXxLFC
"""

import pandas as pd

def show_info(df):
    """Displays information about the DataFrame, including data types and memory usage."""
    print("DataFrame Info:\n")
    print(df.info())

def show_missing_values(df):
    """Displays the number of missing values in each column."""
    print("Missing Values:\n")
    print(df.isnull().sum())

def show_summary_statistics(df):
    """Displays basic statistical measures for numerical columns."""
    print("Summary Statistics:\n")
    print(df.describe())

def show_value_counts(df, column):
    """Displays the frequency of unique values in a specified column."""
    print(f"Value Counts for {column}:\n")
    print(df[column].value_counts())

def show_column_types(df):
    """Displays the data types of each column."""
    print("Column Data Types:\n")
    print(df.dtypes)

def show_unique_values(df, column):
    """Displays unique values in a specified column."""
    print(f"Unique Values in {column}:\n")
    print(df[column].unique())

def show_duplicates(df):
    """Displays the count of duplicate rows."""
    duplicates = df.duplicated().sum()
    print(f"Number of duplicate rows: {duplicates}")

def show_correlation_matrix(df):
    """Displays the correlation matrix for numerical columns."""
    print("Correlation Matrix:\n")
    print(df.corr())

def show_head(df, n=5):
    """Displays the first n rows of the DataFrame (default: 5 rows)."""
    print(f"First {n} Rows of DataFrame:\n")
    print(df.head(n))

def show_tail(df, n=5):
    """Displays the last n rows of the DataFrame (default: 5 rows)."""
    print(f"Last {n} Rows of DataFrame:\n")
    print(df.tail(n))

def show_shape(df):
    """Displays the shape of the DataFrame."""
    print("Shape of the DataFrame (rows, columns):\n")
    print(df.shape)

def show_memory_usage(df):
    """Displays the memory usage of the DataFrame."""
    print("Memory Usage:\n")
    print(df.memory_usage(deep=True))

def show_column_stats(df, column):
    """Displays statistics for a specific column, including mean, median, and standard deviation."""
    print(f"Statistics for {column}:\n")
    print(f"Mean: {df[column].mean()}")
    print(f"Median: {df[column].median()}")
    print(f"Standard Deviation: {df[column].std()}")

def show_null_percentage(df):
    """Displays the percentage of missing values for each column."""
    null_percentage = (df.isnull().sum() / len(df)) * 100
    print("Percentage of Missing Values by Column:\n")
    print(null_percentage)

def show_skewness(df):
    """Displays the skewness of numerical columns in the DataFrame."""
    print("Skewness of Numerical Columns:\n")
    print(df.skew())

